name: vr_player
description: The `VrPlayer` lets you play 360Â° and VR videos smoothly on Android and iOS platforms
version: 0.2.0
homepage: "https://github.com/What-the-Flutter/VR-Player"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: wtf.flutter.vr_player
        pluginClass: VrPlayer
      ios:
        pluginClass: VrPlayer
